keys:
  - &Felix-yubikey 499C66E9512BA96797CDAC410562840F5B0C9BD4
  - &teefax-test 836578108a97d170fcd5b11b9ba0839b3899dbb0
creation_rules:
  - path_regex: nixos/secrets/.*
    key_groups:
    - pgp:
        - *Felix-yubikey
        - *teefax-test
