keys:
  - &Felix-yubikey 499C66E9512BA96797CDAC410562840F5B0C9BD4
  - &Florian-Admin CFAA36038DF83F58F38090E2358EE66F828961B3
  - &teefax cebeae9995e7e299c890ea0037889e2d9e9b58e1
  - &Arthur age1n9e7ymdmcprdynwutygfvd6an2h9xcvpneehu9gcsd93vr0mvg5sqndy08
  - &testfax 53442408c43a1ad985496b314a1e7a4bfdb0852b
  - &Robert AF4FA38CDA30CFF20BC2AE9890AE3884EC0EF08B
creation_rules:
  - path_regex: nixos/secrets/.*
    key_groups:
    - pgp:
        - *Florian-Admin
        - *Felix-yubikey
        - *teefax
        - *testfax
      age:
        - *Arthur
