keys:
  - &Felix-yubikey BF91E7F996966393DF5992FE15215F777DC602FC
  - &teefax-test 491b8e56e49f83353afe3965be1f8cb5216ea5e5
creation_rules:
  - path_regex: nixos/secrets/.*
    key_groups:
    - pgp:
        - *Felix-yubikey
        - *teefax-test
