server:
  http_listen_port: 28183
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://127.0.0.1:3100/loki/api/v1/push

scrape_configs:
 - job_name: system
   static_configs:
   - targets:
      - localhost
     labels:
      job: logs
      host: teefax
      __path__: /var/log/other/*/*.log
   - targets:
      - localhost
     labels:
      job: traefik
      host: teefax
      __path__: /var/log/*.log
