  groups:
    - name: TraefikMonitoring
      rules:
      - alert: TraefikServiceDown
        expr: traefik_service_server_up == 0
        for: 0m
        labels:
          severity: critical
        annotations:
          description: "Traefik service down {{ $labels.service }}"
